services:
  citygems_db_secu_design:
    image: mysql:latest
    container_name: mysqldb_secu_design
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: city_gems_db
    healthcheck:
      test: mysqladmin ping -h localhost --user=$$MYSQL_USER --password=$$MYSQL_ROOT_PASSWORD
      interval: 30s
      timeout: 12s
      retries: 10  

  citygems_api_secu_design:
    build: .
    container_name: node_api_secu_design
    ports:
      - "3004:3004"
    environment:
      DATABASE_URL: mysql://root:root@citygems_db_secu_design:3306/city_gems_db
      DB_HOST:  citygems_db_secu_design
      JWT_KEY: root
      JWT_REFRESH_KEY: root
      NODE_ENV: development
    depends_on:
      - citygems_db_secu_design

volumes:
  db_data:
